### ISSUE TITLE
Slidev server not found

### ISSUE THREAD

**Issue by JamesYuuu** [slidevjs/slidev-vscode#18]
Hi there, I use `npx slidev` to run a slidev server in terminal but the plugin still shows slidev server is not found. 
How to fix this problem?
![image](https://user-images.githubusercontent.com/95520900/198880874-306701d7-ee56-4767-910f-8b925580aaf7.png)

**Comment by kubukoz** [comment]
Seeing the same, even with a custom port (using yarn).

**Comment by prvst** [comment]
I'm using the latest version and it's also not working.

**Comment by GNKurtlar** [comment]
I have the same issue.

**Comment by wey-gu** [comment]
same here.

**Comment by moreant** [comment]
same here.

**Comment by kermanx** [comment]
We've rewritten the VSCode extension for Slidev (https://github.com/slidevjs/slidev/pull/1557). Upgrading the VSCode extension to the latest (`0.49.1`) can fix this issue.

Note that in the latest version the VSCode extension starts the Slidev CLI from the local package rather than the global intallation (i.e. the one installed via `npm i -g @slidev/cli`)
