### ISSUE TITLE
Slidev server not found on `http://localhost:3030/`

### ISSUE THREAD

**Issue by leo91000** [slidevjs/slidev-vscode#8]
I get the following message on VSCode :
![image](https://user-images.githubusercontent.com/1354510/127736684-aa17a36d-fa7d-4915-a020-854a6c66b487.png)

However my server is up and running on `http://localhost:3030/`
If I hit reload in the top right corner of the preview pannel, it does nothing.
I am using VSCode 1.58.0 on windows on slidev-vscode 0.3.2

_--- Edit :_
It seems that if I start my server, **then** I start VSCode it works. Maybe it is just a reload problem.

**Comment by SulfurZinc** [comment]
@leo91000 ,hi leo, I am totally new to this. Could I ask, how to start the slidev server after it's shut down. I tried to run"npm init slidev" but it will create a new project, which is not what I want.

**Comment by hejfelix** [comment]
I second this, I can't make it work no matter when I start the server. Works fine in my browser.

**Comment by Shinigami92** [comment]
I'm also affected by this issue

**Comment by PeterWang-dev** [comment]
same issue on archlinux

**Comment by Mickychen00** [comment]
Same issue in mac arm64 and windows10

**Comment by wakuflair** [comment]
Same issue

**Comment by Delta-in-hub** [comment]
Same issue

**Comment by NonurSis** [comment]
Has anyone found a solution?

**Comment by AsakuraMizu** [comment]
workaround: add `--remote` option when starting slidev

**Comment by AsakuraMizu** [comment]
After some investigation, I figured out it's caused by the same problem as vitest-dev/vscode#55. Newer versions of node resolve `localhost` to `::1` while older ones (under 17) resolve `localhost` to `127.0.0.1`. Unfortunately, VS Code uses node16.  
As [#issuecomment-1272985138](https://github.com/vitest-dev/vscode/issues/55#issuecomment-1272985138) commented out, the issue could be solved by adding `dns.setDefaultResultOrder("verbatim")`, but it's not a good practice.
